-- BertBooker — the D1 schema.
-- Applied via: wrangler d1 migrations apply bertbooker_db [--local|--remote]
--
-- This is the whole schema in one file. Program reference rows are seeded
-- separately by seed/programs.sql, and airport rows by seed/airports.sql; both
-- live outside migrations/ so they stay re-runnable.
--
-- Statement order follows the foreign keys, which D1 enforces: `programs` and
-- `users` before anything referencing them, `search_runs` before the three
-- tables that cascade off it, `tracked_routes` before `alert_outbox`.


-- ===========================================================================
-- Reference data
-- ===========================================================================

-- Loyalty programs and how the couple's currencies feed them.
-- Mirrors shared/src/data/programs.ts — keep the two in sync.
CREATE TABLE IF NOT EXISTS programs (
  code              TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  kind              TEXT NOT NULL CHECK (kind IN ('airline', 'hotel')),
  alliance          TEXT,                       -- 'star'|'oneworld'|'skyteam'|NULL
  transfer_partners TEXT NOT NULL DEFAULT '[]', -- JSON: [{currency, ratio}]
  is_active         INTEGER NOT NULL DEFAULT 1
);

-- Airport reference data (searchable). Rows come from seed/airports.sql,
-- generated by scripts/build-airports.mjs from the public-domain OurAirports
-- dataset. Standalone: no FK points at it and it points at nothing.
CREATE TABLE IF NOT EXISTS airports (
  ident     TEXT PRIMARY KEY,   -- OurAirports unique identifier (e.g. KJFK)
  type      TEXT,               -- large_airport | medium_airport | heliport | ...
  name      TEXT NOT NULL,
  iata      TEXT,               -- IATA code (may be empty for non-commercial fields)
  icao      TEXT,               -- ICAO / GPS code
  city      TEXT,               -- municipality
  country   TEXT,               -- ISO 3166-1 alpha-2
  region    TEXT,               -- ISO 3166-2 region
  continent TEXT,
  latitude  REAL,
  longitude REAL,
  scheduled INTEGER NOT NULL DEFAULT 0  -- 1 if the airport has scheduled service
);
CREATE INDEX IF NOT EXISTS idx_airports_iata ON airports(iata);
CREATE INDEX IF NOT EXISTS idx_airports_name ON airports(name);
CREATE INDEX IF NOT EXISTS idx_airports_city ON airports(city);

-- The two people using the app. There is no Cloudflare Access in front of this
-- worker, so identity is the single shared `APP_USER_EMAIL` behind the password
-- gate — `Cf-Access-Authenticated-User-Email` is deliberately ignored
-- (api/src/identity.ts).
CREATE TABLE IF NOT EXISTS users (
  email        TEXT PRIMARY KEY,
  display_name TEXT,
  created_at   INTEGER NOT NULL DEFAULT (unixepoch() * 1000)
);


-- ===========================================================================
-- What the user asked for
-- ===========================================================================

-- A monitored route: a SET of city pairs, a date window, and the filters that
-- narrow its finds.
--
-- `origins`/`destinations` are nullable JSON arrays beside the scalar
-- `origin`/`destination`, which stay as the route's PRIMARY airport. Readers use
-- COALESCE(origins, json_array(origin)), so a row carrying only the scalar still
-- works. `cabins` and `currencies` have the same shape and the same rule: NULL
-- means "no filter", not "none".
--
-- Searching SEA/PDX -> NRT/HND is the cross product of two airport lists. A
-- route expands into a pair list, and everything downstream — the search plan,
-- the coverage claim, the prune — already works per pair because co-terminal
-- answers forced it to (see `routesTouched` in
-- shared/src/ingest/apply.ts). shared/src/routing.ts turns this
-- into pair groups; ONE group is ONE seats.aero call however many pairs it
-- holds, because the API takes comma-delimited airports.
CREATE TABLE IF NOT EXISTS tracked_routes (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  user_email      TEXT NOT NULL REFERENCES users(email),
  origin          TEXT NOT NULL,   -- IATA; the route's primary origin
  destination     TEXT NOT NULL,   -- IATA; the route's primary destination
  origins         TEXT,            -- JSON array of IATA; NULL = use the scalar
  destinations    TEXT,            -- JSON array of IATA; NULL = use the scalar
  date_start      TEXT NOT NULL,   -- ISO date
  date_end        TEXT NOT NULL,   -- ISO date (inclusive)
  -- A representative cabin, still written on insert. `cabins` is what actually
  -- filters the route's finds.
  cabin           TEXT NOT NULL DEFAULT 'business',
  cabins          TEXT,            -- JSON array of cabin codes; NULL = any
  currencies      TEXT,            -- JSON array of currency codes; NULL = any
  min_seats       INTEGER NOT NULL DEFAULT 2,
  programs        TEXT,            -- JSON array of program codes; NULL = all
  kind            TEXT NOT NULL DEFAULT 'flight' CHECK (kind IN ('flight', 'hotel')),
  hotel_id        TEXT,
  last_checked_at INTEGER,
  created_at      INTEGER NOT NULL DEFAULT (unixepoch() * 1000),

  -- A READ filter, and only a read filter. Gather wide, query narrow:
  -- connecting itineraries are still gathered, still stored and still claim
  -- coverage; this decides only what the route's own pane shows. It is applied
  -- in the Routes page join beside `cabins` / `currencies` / `min_seats`, which is
  -- the one place a route's filters are ever applied — nothing about the search
  -- plan or the coverage claim reads it, and nothing may.
  direct_only     INTEGER NOT NULL DEFAULT 0,

  -- The one per-route setting that changes what is GATHERED, not merely what is
  -- shown, and the difference is the whole point: a round trip needs award space
  -- in BOTH directions, and no filter can surface data that was never fetched.
  --
  -- It is nearly free, which is what makes it a checkbox rather than a second
  -- route. seats.aero takes comma-delimited airports, so a round-trip search
  -- puts every airport on BOTH sides of one call —
  -- `origin_airport=HND,SEA&destination_airport=HND,SEA` returns SEA->HND and
  -- HND->SEA together, with the self-pairs dropped by `routePairs`. Same chunks,
  -- same call count, same quota as the one-way search it replaces. See
  -- `roundTripSpec` in shared/src/routing.ts.
  --
  -- Two consequences worth knowing:
  --   * The ROUTES PAGE JOIN must match both directions for these routes, or the
  --     return legs this gathers would be stored and invisible.
  --   * Roughly twice the rows come back per chunk, so a busy route is likelier
  --     to paginate out at SEATSAERO_MAX_PAGES. That NARROWS the coverage claim
  --     honestly (`runSeatsAeroChunk` claims only through the furthest date it
  --     actually saw); it does not corrupt anything.
  round_trip      INTEGER NOT NULL DEFAULT 0,

  -- -------------------------------------------------------------------------
  -- Alerts (api/src/alerts/, docs/ALERTS.md)
  -- -------------------------------------------------------------------------

  -- Off by default, so a newly created route schedules nothing.
  alerts_enabled  INTEGER NOT NULL DEFAULT 0,

  -- Where the digest goes. NULL = the route's own `user_email`, which is the
  -- shared identity — so the common case needs no decision. Writes are checked
  -- against ALERT_ALLOWED_RECIPIENTS: with one shared password as the only auth,
  -- an unchecked value here would make the Worker an arbitrary-recipient sender
  -- on a verified domain, and the domain's sending reputation is not something a
  -- typo should be able to spend.
  alert_email     TEXT,

  -- JSON array of ChangeType (shared/src/diff.ts): new | more_seats |
  -- price_drop | gone. NULL = the default set, ["new","price_drop"].
  --
  -- READ THIS BEFORE COPYING THE NEIGHBOURING COLUMNS' CONVENTION. `cabins` and
  -- `currencies` treat NULL *and* `[]` alike as "no filter, everything matches".
  -- Here `[]` would mean the opposite — nothing ever fires — so it is REJECTED
  -- at the API with a 400 rather than stored. NULL is the only way to say
  -- "default". A route with alerts on and no type selected is a route that
  -- silently never alerts, which is the single most plausible way for this
  -- feature to look broken while behaving exactly as configured.
  --
  -- `gone` is not in the default set on purpose: most disappearances are cache
  -- churn or dates ageing out of the window, and it is the one type that cannot
  -- be intersected against the finds query (there is no current row left to
  -- filter), so it honours fewer of the route's filters than the others do.
  alert_on        TEXT,

  -- Minimum price drop, in percent, before `price_drop` is worth an email.
  -- Defaults to 5 rather than 0: seats.aero re-quotes constantly and a 1%
  -- movement is noise that would train you to ignore the mail.
  alert_min_drop_pct INTEGER NOT NULL DEFAULT 5,

  -- THREE CLOCKS, and each one is load-bearing. Collapsing any two re-creates a
  -- bug the others exist to prevent.
  --
  --   last_checked_at        (above) "this route holds real data as of…"
  --                          Written ONLY when a run claimed coverage. Consulted
  --                          by the scheduler as a floor, so a route searched by
  --                          hand five minutes ago is not immediately re-swept.
  --
  --   alert_last_attempt_at  THE PACING CLOCK. Written on every sweep attempt,
  --                          success or failure. Pacing off `last_checked_at`
  --                          instead would hot-loop a permanently-failing route
  --                          forever: that column is never written when a run
  --                          fails, so the route would be due on every single
  --                          tick and burn the day's allowance on a route that
  --                          cannot succeed.
  --
  --   alert_last_digest_at   THE EMAIL CLOCK, and what makes the first sweep
  --                          silent. `diffAvailability` compares against the last
  --                          snapshot FOR THAT SOURCE, so a route that has not
  --                          been searched recently classifies everything it
  --                          finds as `new` plus a wall of `gone` — thousands of
  --                          changes, truncated to MAX_STORED_CHANGES, emailed as
  --                          a meaningless 200-of-3000 digest. A route with this
  --                          NULL therefore performs a BASELINE sweep: it ingests
  --                          normally, emails nothing, and just stamps this
  --                          column. Same rule when alerts are re-enabled on a
  --                          route that has gone dark.
  alert_last_attempt_at INTEGER,
  alert_last_digest_at  INTEGER,

  -- Consecutive failed sweeps, for exponential backoff. Without it a route with
  -- a window entirely in the past, or a spec seats.aero refuses, takes a slot in
  -- every cycle forever — and it is the likeliest real-world fault, because a
  -- date window silently expires just by time passing. Reset to 0 on any sweep
  -- that claims coverage.
  alert_consecutive_failures INTEGER NOT NULL DEFAULT 0
);
-- The scheduler's one hot query is "which alert-enabled route is most overdue".
-- Partial, because alert-enabled routes are a handful out of the table.
CREATE INDEX IF NOT EXISTS idx_tracked_routes_alerts
  ON tracked_routes (alert_last_attempt_at)
  WHERE alerts_enabled = 1;


-- ===========================================================================
-- What was found
-- ===========================================================================

-- THE core availability table — normalized, provider-agnostic. One row per
-- (route, date, program, cabin, source) observation, written only when the
-- source's claim changed.
--
-- Rows are current PER SOURCE rather than merged before write. Reads take the
-- latest per (route_key, program, cabin, source) and then collapse across
-- sources by source_fetched_at (see api/src/finds.ts). That keeps every
-- source's claim on the record — disagreement becomes a query instead of a log
-- line that discarded one side — and it is what makes per-source pruning safe.
--
-- There is one source now, so the collapse resolves trivially. The scoping is
-- kept anyway: it is what makes retiring a source a data question with a right
-- answer (delete its rows — see 0002) rather than a silent corruption.
CREATE TABLE IF NOT EXISTS availability_snapshots (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  route_key           TEXT NOT NULL,   -- 'JFK-DXB-2026-11-14'
  origin              TEXT NOT NULL,
  destination         TEXT NOT NULL,
  flight_date         TEXT NOT NULL,   -- ISO date
  program             TEXT NOT NULL REFERENCES programs(code),
  cabin               TEXT NOT NULL,
  seats_available     INTEGER NOT NULL,
  miles_cost          INTEGER NOT NULL,
  -- The residual tax owed on top of an award redemption. NOT the portal price —
  -- see cash_price_cents below, which answers a different question.
  cash_fees_cents     INTEGER NOT NULL DEFAULT 0,
  fees_currency       TEXT NOT NULL DEFAULT 'USD',
  is_direct           INTEGER NOT NULL DEFAULT 0,
  segments_json       TEXT NOT NULL DEFAULT '[]',
  -- The source plug-in id (shared/src/sources/). 'seatsaero' is the only value
  -- written today; 'pointsyeah' was the other, and 0002 deleted its rows. A
  -- PERMANENT STORED VALUE — it is what a prune is scoped to and what a read
  -- collapses on, so renaming one orphans every row that carries it, and
  -- RETIRING one without deleting its rows leaves them current forever.
  source              TEXT NOT NULL,
  -- When the SOURCE observed it. For seats.aero this is their `UpdatedAt` cache
  -- stamp, not our fetch time: findsCte picks winners by freshest
  -- source_fetched_at, and substituting the fetch time would let a week-old
  -- cached row out-rank a fresher observation from another source.
  source_fetched_at   INTEGER NOT NULL,
  captured_at         INTEGER NOT NULL DEFAULT (unixepoch() * 1000),

  -- What the SOURCE said when this row was written. Ingest is write-on-change
  -- against the STORED value (`loadPreviousForSource`), never against a hash
  -- recomputed from the row — enrichment rewrites segments_json in place and
  -- leaves this alone, so the two legitimately disagree, and re-hashing would
  -- see every enriched row as changed and rewrite it back to a summary on the
  -- next search.
  raw_hash            TEXT NOT NULL,

  -- The couple's currencies that can book this, from the source's transfer info.
  -- JSON array, e.g. ["chase_ur","bilt"]. Read by BOOKABLE_WITH_CLAUSE.
  transfer_currencies TEXT NOT NULL DEFAULT '[]',

  duration_minutes    INTEGER,
  booking_url         TEXT,

  -- The PORTAL fare for the same itinerary, so the app can show what a seat
  -- costs in dollars beside what it costs in miles. Nullable on purpose: NULL
  -- means "no source could see a fare", which is a different fact from 0. Do not
  -- confuse with cash_fees_cents above.
  cash_price_cents    INTEGER,
  cash_price_currency TEXT,

  -- Traces a find back to the run that produced it. Deliberately not an FK:
  -- a run row may be pruned before the finds it wrote.
  search_run_id       TEXT,

  --   source_record_id  the source's own id for the availability record. It is
  --                     the HANDLE the detail fetch needs, and one id covers all
  --                     four cabins of a (route, date, program) — so one call
  --                     enriches up to four rows here. NULL for sources that
  --                     expose no such id.
  --   detail_level      'summary' = one synthetic segment, no flight numbers.
  --                     'itinerary' = real legs. Defaults to 'itinerary' because
  --                     that is what every other source already produces.
  --   enriched_at       when a detail fetch was last spent on this row. Set even
  --                     when the fetch came back with nothing usable, which is
  --                     the difference between "not tried yet" and "tried, the
  --                     source had no itinerary at this price" — without it the
  --                     UI would invite the same wasted call forever.
  source_record_id    TEXT,
  detail_level        TEXT NOT NULL DEFAULT 'itinerary'
                        CHECK (detail_level IN ('summary', 'itinerary')),
  enriched_at         INTEGER,

  -- How many stops, or NULL for GENUINELY UNKNOWN. Nullable is the whole point:
  -- seats.aero's Cached Search, asked without `include_trips`, reports that a
  -- connecting award exists and never says how many stops it has. A NOT NULL
  -- column cannot express that and would launder a guess into data.
  stop_count          INTEGER,

  -- Every carrier on any itinerary for this row, and the subset that flies it
  -- NONSTOP. The pair matters more than it looks: a captured SFO->NRT row read
  -- `YAirlines: "AS, CX, JL, JX, PR"` beside `YDirectAirlines: "JL"`, so taking
  -- airlines[0] labelled a nonstop row "AS" — the one carrier that specifically
  -- does not fly it nonstop.
  airlines            TEXT,   -- JSON array
  direct_airlines     TEXT,   -- JSON array, often empty

  -- What the nonstop costs, when one exists. Deliberately an ATTRIBUTE of this
  -- row, not a second row: a nonstop at a different price is a different award,
  -- but it would collide on (route_key, program, cabin) — the exact
  -- non-determinism `collapseBy` exists to prevent. Store it; never insert it.
  direct_miles_cost   INTEGER
);
CREATE INDEX IF NOT EXISTS idx_snap_lookup
  ON availability_snapshots (route_key, program, cabin, captured_at);
CREATE INDEX IF NOT EXISTS idx_snap_captured
  ON availability_snapshots (captured_at);
-- The per-source lookup the read path needs.
CREATE INDEX IF NOT EXISTS idx_snap_source_lookup
  ON availability_snapshots (route_key, program, cabin, source, captured_at DESC);
-- The enrich endpoints look rows up by availability id (to expand one) and scan
-- for un-enriched ones (to offer "enrich all"). The partial index keeps it to
-- the rows that can actually be enriched.
CREATE INDEX IF NOT EXISTS idx_snap_enrich
  ON availability_snapshots (source_record_id, detail_level)
  WHERE source_record_id IS NOT NULL;


-- ===========================================================================
-- How the finding went
-- ===========================================================================
--
-- Coverage is a STORED FACT, not a transient in-memory claim. Gathering can
-- happen on a laptop, minutes or weeks before the query that reads it, so "did
-- anyone actually look at (route, date, program)?" needs a table — or every
-- absence becomes ambiguous again, and an ambiguous absence deletes real finds.
--
-- These tables are named for the SEARCH, not for any one runner. A search a
-- human pressed for and a scheduled alert sweep are structurally the same thing:
-- each opens a run, records tasks against it and claims coverage. A third kind
-- of runner used to write here too, from outside Cloudflare; 0002 deleted its
-- rows. (`search_logs` was the fourth table in this group, dropped by 0002.)

-- One search: a Worker-side run, or one alert sweep's share.
CREATE TABLE IF NOT EXISTS search_runs (
  id             TEXT PRIMARY KEY,        -- uuid minted by the caller, not the server
  user_email     TEXT NOT NULL,
  -- 'cli' | 'ui' | 'search' | 'alert'. No CHECK constraint on purpose: a new
  -- trigger should not need a migration to become storable, which is how the
  -- scheduled sweep joined this table without one.
  trigger        TEXT NOT NULL,
  origin         TEXT NOT NULL,
  destination    TEXT NOT NULL,
  date_start     TEXT NOT NULL,           -- ISO date
  date_end       TEXT NOT NULL,           -- ISO date (inclusive)
  programs_json  TEXT,                    -- requested program filter; NULL = all
  sources_json   TEXT NOT NULL,           -- JSON array of source ids attempted
  status         TEXT NOT NULL DEFAULT 'running'
                   CHECK (status IN ('running', 'ok', 'partial', 'failed', 'aborted')),
  started_at     INTEGER NOT NULL,
  finished_at    INTEGER,
  duration_ms    INTEGER,
  tasks_planned  INTEGER NOT NULL DEFAULT 0,
  tasks_ok       INTEGER NOT NULL DEFAULT 0,
  tasks_failed   INTEGER NOT NULL DEFAULT 0,
  offers_found   INTEGER NOT NULL DEFAULT 0,
  snapshots_written INTEGER NOT NULL DEFAULT 0,
  snapshots_pruned  INTEGER NOT NULL DEFAULT 0,
  changes_json   TEXT,                    -- bounded diff summary; display only
  error          TEXT,
  host           TEXT,                    -- machine that ran it
  -- Which build of the runner produced this run. Only the local gatherer ever
  -- populated it, and 0002 deleted its rows; the Worker leaves it NULL.
  runner_version TEXT,
  created_at     INTEGER NOT NULL DEFAULT (unixepoch() * 1000),

  -- What this run actually SPENT at the metered source. Every other counter here
  -- measures work; this one measures money, and the scheduler needs it twice
  -- over:
  --
  --   * PACING. `estimateSearchCalls` quotes a range, and the range is wide —
  --     one call per date chunk at the floor, ten times that if every chunk
  --     paginates out (5 vs 50 for a year-long route). Dividing a daily
  --     allowance by the floor would underestimate a busy route tenfold, in the
  --     direction that overspends. A route's LAST MEASURED cost is the honest
  --     input, and this is where it lives.
  --
  --   * THE BUDGET GUARD'S FALLBACK. `source_quota.remaining` is only observed
  --     when a call is actually made, so early in a UTC day there is often no row
  --     at all. Refusing to sweep until someone has manually searched would mean
  --     alerts never fire on most days; assuming a full 1000 would overspend on
  --     the one day it mattered. Summing this column over today's runs answers
  --     the question from our own records, and the first real
  --     `X-RateLimit-Remaining` observation then corrects it.
  --
  -- NULL means "this run spent calls nobody counted". `COALESCE(calls, 0) + ?`
  -- on the accumulate path means a resumed run adds to its own total rather than
  -- overwriting it, exactly like the task and snapshot counters beside it.
  calls          INTEGER,

  -- Which tracked route this run was about.
  --
  -- `origin`/`destination` above are only that route's PRIMARY airports (a
  -- SEA/PDX -> NRT/HND route stores SEA and NRT, because those columns are NOT
  -- NULL scalars and a comma-joined "airport" called `SEA,PDX` would be a value
  -- no query could match). So two routes sharing a primary pair and differing by
  -- window or filters are indistinguishable without this, and the alert
  -- scheduler needs to tell them apart for pacing (a route's sweep is priced
  -- from what its OWN last sweep spent) and for the Alerts tab ("show me this
  -- route's sweeps, and whether they are failing").
  --
  -- Nullable, and NULL is correct for a local gather: that is a city pair
  -- someone typed, not a saved route, and inventing an association would be
  -- worse than admitting there is none. Deliberately NOT a foreign key, matching
  -- `search_run_id` on `availability_snapshots` and for the same reason —
  -- deleting a route must not cascade away the history of what was gathered
  -- under it, and a run that outlives its route is still a true record.
  route_id       INTEGER
);
CREATE INDEX IF NOT EXISTS idx_srun_recent   ON search_runs (user_email, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_srun_route    ON search_runs (origin, destination, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_srun_route_id ON search_runs (route_id, started_at DESC);

-- One row per (source, unit of work) — one API call, one date range. This is the
-- "how did it actually go" record, and the whole reason gathering is planned
-- into individually observable tasks: a source that returns nothing and a source
-- that was refused at the door produce identical availability data and
-- completely different rows here.
CREATE TABLE IF NOT EXISTS search_tasks (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id         TEXT NOT NULL REFERENCES search_runs(id) ON DELETE CASCADE,
  source         TEXT NOT NULL,              -- 'seatsaero' (was also 'pointsyeah'; see 0002)
  task_key       TEXT NOT NULL,              -- 'seatsaero:SEA-LAX:2027-03-05'
  origin         TEXT NOT NULL,
  destination    TEXT NOT NULL,
  dates_json     TEXT NOT NULL,              -- JSON array of dates this task asked about
  status         TEXT NOT NULL CHECK (status IN
                   ('ok', 'empty', 'failed', 'skipped', 'blocked', 'challenged', 'timeout')),
  offers_found   INTEGER NOT NULL DEFAULT 0,
  attempts       INTEGER NOT NULL DEFAULT 1,
  started_at     INTEGER NOT NULL,
  finished_at    INTEGER NOT NULL,
  duration_ms    INTEGER NOT NULL,
  error          TEXT,
  final_url      TEXT,
  http_status    INTEGER,
  capture_json   TEXT,                       -- intercepted responses: url, status, bytes
  -- DROPPED BY 0002. A path on the local runner's disk to a failed task's dump;
  -- meaningless from a Worker, which has no disk. Still created here because
  -- this file is the record of what was APPLIED, and 0002 is the delta.
  artifact_path  TEXT,
  -- Ingest applies each task as work completes and may re-apply one, so the
  -- same task can arrive twice. This makes the second arrival an update, not a
  -- duplicate.
  UNIQUE (run_id, source, task_key)
);
CREATE INDEX IF NOT EXISTS idx_stask_run    ON search_tasks (run_id);
CREATE INDEX IF NOT EXISTS idx_stask_source ON search_tasks (source, finished_at DESC);

-- DROPPED BY 0002 — read that migration before reasoning about this table.
--
-- Per-source log lines, durable because the person reading them is not
-- necessarily the person who pressed the button. Its only writer was the
-- `/api/ingest/*` batch handler the local runner POSTed to; the Worker's own
-- search streams NDJSON to the browser instead, and nothing ever read a row
-- back out. It is still created here because this file is the record of what
-- was applied, not a description of the live schema.
CREATE TABLE IF NOT EXISTS search_logs (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id      TEXT NOT NULL REFERENCES search_runs(id) ON DELETE CASCADE,
  source      TEXT,                          -- NULL for run-level lines
  at_ms       INTEGER NOT NULL,              -- ms since run start
  level       TEXT NOT NULL DEFAULT 'info' CHECK (level IN ('info', 'warn', 'error')),
  message     TEXT NOT NULL,
  fields_json TEXT
);
CREATE INDEX IF NOT EXISTS idx_slog_run ON search_logs (run_id, at_ms);

-- What was LOOKED AT, by whom, and when.
--
-- INVARIANT (the one that destroys data if broken): a row here is a claim that
-- this source searched this slice and its findings are the complete truth for
-- it. Only write one for a task that SUCCEEDED — `ok` or `empty`. A task that
-- threw, was skipped, blocked, challenged or timed out claims nothing, which is
-- what stops its stored finds being deleted as "vanished" by a run that never
-- looked.
--
-- Keyed per SOURCE, so one source's failure can never prune another's data.
-- Upserted, so it always holds the most recent check per slice.
--
-- `origin` and `destination` are single airports and MUST NEVER contain a comma.
-- A multi-pair task claims coverage for every pair it asked about by fanning out
-- into one row each; an "airport" called 'SEA,PDX' would store happily and match
-- nothing ever again, leaving the real pairs looking unchecked while the pruner
-- believed otherwise. Pinned by a test.
CREATE TABLE IF NOT EXISTS search_coverage (
  origin       TEXT NOT NULL,
  destination  TEXT NOT NULL,
  flight_date  TEXT NOT NULL,
  program      TEXT NOT NULL REFERENCES programs(code),
  source       TEXT NOT NULL,
  run_id       TEXT NOT NULL REFERENCES search_runs(id) ON DELETE CASCADE,
  checked_at   INTEGER NOT NULL,
  offers_found INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (origin, destination, flight_date, program, source)
);
-- Answers "how stale is this find" and "which dates in my window has nobody ever
-- checked" without scanning per-source rows.
--
-- DROPPED BY 0005, and replaced by idx_scov_current, which carries `program`
-- between `flight_date` and `checked_at`. Its one reader was the `coverage` CTE
-- in db/finds.ts, which grouped the WHOLE table on every read; once that became
-- a correlated per-slice MAX() the missing `program` column was what stood
-- between the lookup and a single seek.
CREATE INDEX IF NOT EXISTS idx_scov_freshness
  ON search_coverage (origin, destination, flight_date, checked_at DESC);

-- Remaining daily API allowance for a metered source, as the vendor last
-- reported it.
--
-- Added for seats.aero, whose Pro key buys 1000 Partner API calls per UTC day
-- and returns the remainder on an `X-RateLimit-Remaining` header. `search.ts`
-- and `enrich.ts` read that header off every response and write it here through
-- the shared `recordQuota`, so the number is readable from anywhere else —
-- including a phone.
--
-- EXACTLY ONE READER MAY GATE ON THIS: `alerts/budget.ts`. Unattended work is
-- what a budget guard is for; a person pressing Search is not, and turning their
-- deliberate action into a confusing refusal is why the guard was deleted from
-- the interactive paths in the first place. `search.ts` and `enrich.ts` still
-- spend first and report after. A guard anywhere else is the deleted one leaking
-- back — see docs/ALERTS.md §1 for the full argument.
--
-- One row per (source, UTC day). `day` is UTC because that is when seats.aero's
-- allowance resets, regardless of where the caller is standing.
CREATE TABLE IF NOT EXISTS source_quota (
  source      TEXT    NOT NULL,          -- source plug-in id, e.g. 'seatsaero'
  day         TEXT    NOT NULL,          -- 'YYYY-MM-DD', UTC
  remaining   INTEGER NOT NULL,          -- calls left when last observed
  limit_calls INTEGER,                   -- daily ceiling; NULL when unstated
  observed_at INTEGER NOT NULL,          -- unix ms
  PRIMARY KEY (source, day)
);


-- ===========================================================================
-- What the alerts sent, and what is waiting to be sent
-- ===========================================================================

-- One row per email the scheduler tried to send.
--
-- The audit trail is not optional here. No failure email is ever sent, so if a
-- digest is dropped — a refused Resend key, an unverified sender domain, a
-- recipient off the allowlist — there is no other trace that it happened, and
-- the symptom is a quiet inbox, which is indistinguishable from "nothing
-- changed". `status = 'failed'` with the provider's own body in `error` is what
-- makes that difference visible in the Alerts tab.
--
-- `sweep_id` is a uuid minted per scheduler invocation, not a foreign key: one
-- sweep can cover several routes and therefore several `search_runs` rows,
-- which is what `run_ids_json` records. There is deliberately no `alert_sweeps`
-- table — it would hold nothing these two columns do not already answer.
--
-- UNIQUE (sweep_id, to_email) is the idempotency backstop: one digest per
-- recipient per sweep, so a retry after a partial failure cannot double-send.
-- The Resend request carries a matching Idempotency-Key for the same reason on
-- the provider's side.
CREATE TABLE IF NOT EXISTS alert_deliveries (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  sweep_id            TEXT NOT NULL,
  to_email            TEXT NOT NULL,
  -- 'sent'    the provider accepted it
  -- 'failed'  we tried and it was refused; `error` says what came back
  -- 'skipped' we did not try; `error` says why (no API key, recipient not
  --           allowed). Distinct from 'failed' because one is our configuration
  --           and the other is theirs.
  status              TEXT NOT NULL CHECK (status IN ('sent', 'failed', 'skipped')),
  subject             TEXT,
  change_count        INTEGER NOT NULL DEFAULT 0,
  route_ids_json      TEXT NOT NULL DEFAULT '[]',
  run_ids_json        TEXT NOT NULL DEFAULT '[]',
  provider_message_id TEXT,
  error               TEXT,
  created_at          INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
  UNIQUE (sweep_id, to_email)
);
CREATE INDEX IF NOT EXISTS idx_alert_deliveries_recent
  ON alert_deliveries (created_at DESC);

-- Alertable changes that have not been emailed yet.
--
-- This table exists because of a scheduling constraint, and the constraint is
-- worth stating: a Cron Trigger with an interval under one hour gets 30 SECONDS
-- of CPU (an hourly one would get 15 minutes). So a tick sweeps ONE route and
-- may pause mid-window, resuming on the next tick through the same
-- `run_continue` mechanism the HTTP search uses. But the product rule is one
-- digest per sweep CYCLE, grouped by route. Those two only coexist if a change
-- outlives the tick that found it — hence an outbox.
--
-- It also means a tick that dies loses nothing: the flush is a separate step
-- from the sweep, and anything already here is still here next time.
--
-- UNIQUE (route_id, change_key) with newest-wins on conflict: a route swept
-- twice before a flush must not put the same seat in one digest twice, and the
-- later observation is the true one.
--
-- `change_key` is `diff.ts`'s `changeKey` — route_key|program|cabin — and is
-- scoped by `route_id` because two tracked routes can legitimately watch the
-- same city pair with different filters and different recipients.
CREATE TABLE IF NOT EXISTS alert_outbox (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  route_id      INTEGER NOT NULL REFERENCES tracked_routes(id) ON DELETE CASCADE,
  change_key    TEXT NOT NULL,
  -- ChangeType, unconstrained for the same reason search_runs.trigger is: a new
  -- transition type should not need a migration to become storable.
  type          TEXT NOT NULL,
  origin        TEXT NOT NULL,
  destination   TEXT NOT NULL,
  flight_date   TEXT NOT NULL,
  program       TEXT NOT NULL,
  cabin         TEXT NOT NULL,
  -- Absent for 'gone' (there is no current result) — nullable, exactly as
  -- ChangeSummary's optional fields are.
  miles_cost    INTEGER,
  seats         INTEGER,
  -- Absent for 'new' (there is no prior result).
  prev_miles    INTEGER,
  prev_seats    INTEGER,
  detected_at   INTEGER NOT NULL,
  run_id        TEXT NOT NULL,
  UNIQUE (route_id, change_key)
);
CREATE INDEX IF NOT EXISTS idx_alert_outbox_route ON alert_outbox (route_id);
