-- Hub airports a route routes THROUGH, so one tracked route can monitor several
-- paths instead of the user keeping a sibling route per leg.
--
-- Purely ADDITIVE: one nullable column on an existing table. No row is touched,
-- nothing is dropped, and every existing route reads exactly as it did — NULL
-- means "no hubs", which is the same shape `cabins` and `currencies` already use
-- for "no filter" and which `parseCodeList` already reads that way.
--
-- WHY THIS IS A COLUMN AND NOT THREE MORE ROUTES.
-- seats.aero holds availability per monitored MARKET, so a pair no program is
-- monitored on (SFO-KTM is in nobody's graph) returns nothing from every search
-- forever. It is still reachable through ICN, DEL or HKG, and the app's first
-- answer was to track each leg as its own route and rejoin them at read time.
-- That works and reads badly: the rail fills with fragments, each needs its own
-- search, and the route you actually care about says nothing about what it is
-- made of. The hubs belong to the route.
--
-- WHAT IT COSTS. A route with hubs plans TWO seats.aero queries per date range
-- instead of one -- origins to (destinations + hubs), then hubs to destinations.
-- It cannot be one query: a cross product rides in a single call, but SFO-ICN
-- and ICN-KTM are different markets and no single origin/destination pair of
-- lists names both without also asking for hub-to-hub pairs nobody wants. So a
-- year-long route goes from 5 calls to 10, against 1000 a day.
--
-- The cap is THREE hubs, enforced in the wire contract (MAX_VIA) rather than
-- here: a CHECK constraint on JSON length would be a second place to keep it,
-- and the same reasoning already leaves MAX_ORIGINS out of the schema. Three is
-- what keeps the first query to four markets, which is what keeps it inside
-- SEATSAERO_MAX_PAGES on a busy pair.
--
-- ROUND TRIP IS EXCLUDED, and deliberately not by a constraint. A round trip
-- whose legs each connect is four query groups and a pairing of pairings;
-- `planRoute` ignores `via` when `round_trip = 1` and the form hides the field.
-- Storing a value that is currently ignored is better than a constraint that
-- would have to be migrated away the day that feature lands.

ALTER TABLE tracked_routes ADD COLUMN via TEXT;
