-- Two indexes that nothing reads, on the two tables the alert cron writes most.
-- Both are 0001-era, and both predate the discipline 0005 introduced ("an index
-- that could not be tied to a measured statement was left out") — 0005 applied
-- that rule to its own additions and never went back over the originals. This
-- is that pass.
--
-- Costs measured with `wrangler d1 insights` over 24h on 2026-08-29.

-- ---------------------------------------------------------------------------
-- search_runs: idx_srun_route is dead.
--
-- Every statement in api/ that reads `search_runs`, with the index that serves
-- it. Not one filters, joins or orders by origin/destination:
--
--   db/runs.ts:66            SELECT changes_json ... WHERE id = ?       -> PK
--   search/run.ts:318        SELECT id ... WHERE id = ?                 -> PK
--   alerts/budget.ts:122     SUM(calls) WHERE started_at >= ?           -> idx_srun_started_calls
--   alerts/sweep.ts:140      last finished alert run for a route        -> idx_srun_route_id
--   alerts/sweep.ts:386      the open alert run for a route             -> idx_srun_route_id
--   alerts/sweep.ts:555      COUNT(*) trigger='alert' status='running'  -> idx_srun_trigger_status
--   endpoints/alerts.ts:169  GET /api/alerts/runs                       -> idx_srun_recent
--
-- It went dead in 0008: `search_runs.origin`/`destination` are only a route's
-- PRIMARY airports, so `route_id` became the way to ask about a route and left
-- nothing asking about the pair.
--
-- Worth 225 rows/day — one entry per INSERT, none per UPDATE, since finishRun's
-- SET list (db/runs.ts:80) touches neither column.
--
-- THE OTHER FOUR STAY, and the two expensive ones stay on purpose:
-- idx_srun_trigger_status and idx_srun_started_calls cost 619 rows/day EACH,
-- because `status` and `calls` are both in that SET list. Each is worth 0.6% of
-- the write ceiling and would cost multiples of that against the read ceiling,
-- which is the tighter of the two. Nor is there a cheaper shape available: any
-- index answering "which alert runs are open" must be maintained when a run
-- opens and when it closes, and a partial `WHERE status = 'running'` is
-- re-evaluated on every write that names `status` anyway.
DROP INDEX IF EXISTS idx_srun_route;

-- ---------------------------------------------------------------------------
-- tracked_routes: idx_tracked_routes_alerts exists for a query that moved.
--
-- Its comment in 0001 says the hot query is "which alert-enabled route is most
-- overdue". That query is no longer SQL: `dueRoutes` (alerts/pace.ts) is a pure
-- function over rows `alertRouteRows` already holds in memory. The only
-- surviving SQL reader of the column is `cycleComplete`'s `due` subquery
-- (alerts/sweep.ts:552), ~96 times a day against a table of nine rows.
--
-- It is also the ONLY index on `tracked_routes` (`id INTEGER PRIMARY KEY
-- AUTOINCREMENT` is a rowid alias, so there is no autoindex), which is exactly
-- why `UPDATE tracked_routes SET alert_last_attempt_at = ?` bills 2 rows where
-- the two clock writes beside it bill 1. Dropping it makes the pacing clock
-- cost 1: 293 rows/day at the measured sweep rate, and it stops the cost
-- scaling with how often the cron runs.
--
-- The pacing clock itself is untouched and must stay where it is —
-- alerts/sweep.ts:379 stamps it BEFORE the search, which is the whole mechanism
-- stopping a permanently-failing route being due on every tick.
DROP INDEX IF EXISTS idx_tracked_routes_alerts;
